version: '3.8'
services:
  mysql:
    container_name: module_db
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD: 'secret_root_password'
      - MYSQL_DATABASE: modules
      - MYSQL_USER: 'loginMySql'
      - MYSQL_PASSWORD: 'secret654'
    ports:
      - 3307:3306      
    volumes:
      - dbdata:/var/lib/mysql
volumes:
    dbdata: